#!/bin/sh

# -----------------------------------------------------------------------------
# Generate airfoil stl
# Make 3D mesh in slab of cells.
cd airfoil_snappyHexMesh
blockMesh > output/1-blockMesh.log 2>&1
surfaceFeatureExtract > output/2-surfaceFeatureExtract.log 2>&1
snappyHexMesh -overwrite > output/3-snappyHexMesh.log 2>&1
rm -f 0/*

# -----------------------------------------------------------------------------
# Make a 2D mesh by extruding a patch and solve to steady state.
cd ../airfoil_simpleFoam
extrudeMesh > output/1-extrudeMesh.log 2>&1
rm -rf 0/*
cp -r 0.org/* 0/
simpleFoam > output/2-simpleFoam.log 2>&1
./liftDrag.plot

# -----------------------------------------------------------------------------
# Copy the mesh from the steady state case and map the results to a
# transient case, then solve transient.
cd ../airfoil_pimpleFoam
cp -r ../airfoil_simpleFoam/constant/polyMesh/* constant/polyMesh/
rm -rf 0/*
cp -r ../airfoil_simpleFoam/0.org/* 0/
rm -f constant/transportProperties
cp ../airfoil_simpleFoam/constant/transportProperties constant/transportProperties
mapFields ../airfoil_simpleFoam -sourceTime latestTime -consistent > output/1-mapFields.log 2>&1
decomposePar > output/2-decomposePar.log 2>&1
mpirun -np 4 pimpleFoam -parallel > output/3-pimpleFoam.log 2>&1
./liftDrag.plot

reconstructPar
